 AWSTemplateFormatVersion: 2010-09-09

 Parameters:
   BucketNme:
     Type: String

 Resources:
   S3Bucket:    
     Type: AWS::S3::Bucket
     Properties:
       BucketName: !Ref BucketNme
       AccessControl: PublicRead
       WebsiteConfiguration:
         IndexDocument: index.html
#        ErrorDocument: error.html
#      DeletionPolicy: Retain

   BucketPolicy:
     Type: AWS::S3::BucketPolicy
     Properties:
       PolicyDocument:
         Id: MyPolicy
         Version: 2012-10-17
         Statement:
           - Sid: PublicReadForGetBucketObjects
             Effect: Allow
             Principal: '*'
             Action: 's3:GetObject'
             Resource: !Join
               - ''
               - - 'arn:aws:s3:::'
                 - !Ref S3Bucket
                 - /*
       Bucket: !Ref S3Bucket			
 
 Outputs:
   WebsiteUrl:
     Value: !GetAtt S3Bucket.WebsiteURL
     Description: URL of Website	

   S3BucketSecureUrl:
     Value: !Join
       - ''
       - - 'https://'
         - !GetAtt S3Bucket.DomainName
     Description: Name of the S3 bucket to hold website content		